server:
  port: 1004

spring:
  datasource:
    caas:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jpashop?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: hrjin@test
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false